//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGDRAPTOR {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Button module using socket 10 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Button button;
        
        /// <summary>The Display_T35 module using sockets 15, 16, 17 and 14 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Display_T35 display;
        
        /// <summary>The UsbClientDP module using socket 8 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClientDP;
        
        /// <summary>The SDCard module using socket 9 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.SDCard sdCard;
        
        /// <summary>The MulticolorLed module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.MulticolorLed led;
        
        /// <summary>The Camera (Premium) module using socket 6 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Camera camera;
        
        /// <summary>The CellularRadio module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.Seeed.CellularRadio cellularRadio;
        
        /// <summary>The MulticolorLed module using socket 1 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.MulticolorLed multicolorLed;
        
        /// <summary>The Button module using socket 13 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Button button2;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZRaptor Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZRaptor)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZRaptor();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.button = new GTM.GHIElectronics.Button(10);
            this.display = new GTM.GHIElectronics.Display_T35(15, 16, 17, 14);
            this.usbClientDP = new GTM.GHIElectronics.UsbClientDP(8);
            this.sdCard = new GTM.GHIElectronics.SDCard(9);
            this.led = new GTM.GHIElectronics.MulticolorLed(3);
            this.camera = new GTM.GHIElectronics.Camera(6);
            this.cellularRadio = new GTM.Seeed.CellularRadio(4);
            this.multicolorLed = new GTM.GHIElectronics.MulticolorLed(1);
            this.button2 = new GTM.GHIElectronics.Button(13);
        }
    }
}
